#!/bin/bash

       #uthor : manuella
       #Date : feb-02-2022


echo "----------------installation of sonarqube is running-------------------"
sleep 2
echo
echo "Step 1: Java 11 installation"
sleep 2
echo
sudo yum update -y
sleep 1
sudo yum install java-11-openjdk-devel -y
sleep 1
sudo yum install java-11-openjdk -y
sleep 2
echo
echo "Step 2: Download SonarQube latest versions on your server"
sleep 2
echo
cd /opt
sleep 1
sudo yum install wget -y
sleep 1
sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.3.0.51899.zip
sleep 2
echo
echo "Step 3: Extract packages"
echo
sleep 2
sudo yum install unzip -y
echo
echo "below tape the letter 'N' to refuse to change version of sonarqube"
echo
sudo unzip /opt/sonarqube-9.3.0.51899.zip
echo
sleep 2
echo
echo "Step 4: Change ownership to the user and Switch to Linux binaries directory to start service"
sleep 2
echo
sleep 1
sudo chown -R vagrant:vagrant /opt/sonarqube-9.3.0.51899
sleep 1
cd /opt/sonarqube-9.3.0.51899/bin/linux-x86-64
sleep 1
./sonar.sh start
sleep 2
echo
echo "Connect to SonaQube"
echo
sleep 2
sudo yum install firewalld -y
sleep 1
sudo systemctl start firewalld
sudo systemctl enable firewalld
sleep 1
sudo systemctl status firewalld
sleep 1
sudo firewall-cmd --permanent --add-port=9000/tcp
echo
sudo firewall-cmd --reload
echo
sudo yum install net-tools -y
sleep 2
echo
echo "----------------the installation of sonarqube is finish------------"
echo
sleep 2
echo "Here are the default credentials for access:"
echo
sleep 2
echo ".Login: unixteam24@gmail.com"
echo
sleep 1
echo ".Password: school1"
echo
